// Character and creature bodies.
//
// The humanoid is 48x72 drawn at 2px a cell. The head is deliberately generous — it
// spans cols 14-33 across rows 1-14 — because headgear has to be able to *enclose* it.
// At the previous resolution a helm was narrower than the skull it sat on and hair
// stuck out either side, which read as a hat balanced on top rather than armour.
//
// Legend:
//   h/H  hair shadow / hair light      k/K  skin / skin shadow      e  eye
//   b/L/B  garment base / light / shadow      a  sleeve
//   l/M  trousers / trousers shadow    s/S  boot / boot light
//   t    tail, horn or ear accent      m  muzzle / mouth

export const HUMANOID = [
  '................................................',
  '..................hhhhhhhhhhhh..................',
  '................hhhhhhhhhhhhhhhh................',
  '...............hhhhhhhhhhhhhhhhhh...............',
  '..............hhhhhhhhhhhhhhhhhhhh..............',
  '..............hhkkkkkkkkkkkkkkkkhh..............',
  '..............hkkkkkkkkkkkkkkkkkkh..............',
  '..............hkkkkkkkkkkkkkkkkkkh..............',
  '..............hkkkeekkkkkkkkeekkkh..............',
  '..............hkkkeekkkkkkkkeekkkh..............',
  '..............hkkkkkkkkkkkkkkkkkkh..............',
  '...............kkkkkkkKKkkkkkkkkk...............',
  '...............kkkkkkkkkkkkkkkkkk...............',
  '................kkkkkkmmmmkkkkkk................',
  '................kkkkkkkkkkkkkkkk................',
  '..................KKKKKKKKKKKK..................',
  '....................kkkkkkkk....................',
  '....................kkkkkkkk....................',
  '..............bbbbbbbbbbbbbbbbbbbb..............',
  '............aabbbbbbbbbbbbbbbbbbbbaa............',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........aaaabbbbbbbbbbbbbbbbbbbbaaaa..........',
  '..........kkkkbbbbbbbbbbbbbbbbbbbbkkkk..........',
  '..........kkkkbbbbbbbbbbbbbbbbbbbbkkkk..........',
  '..............bbbbbbbbbbbbbbbbbbbb..............',
  '..............bbbbbbbbbbbbbbbbbbbb..............',
  '...............bbbbbbbbbbbbbbbbbb...............',
  '...............bbbbbbbbbbbbbbbbbb...............',
  '................llllllllllllllll................',
  '................llllllllllllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................lllllll..lllllll................',
  '................MMMMMMM..MMMMMMM................',
  '................lllllll..lllllll................',
  '..............sssssssss..sssssssss..............',
  '..............sssssssss..sssssssss..............',
  '..............SSSSSSSSS..SSSSSSSSS..............',
];

// A wolf, facing right: pointed ears, a long muzzle, a deep chest, a bushy tail held
// low, and four legs.
export const WOLF = [
  '................................',
  '......................t...t.....',
  '.....................tt...tt....',
  '....................tbb...bbt...',
  '...tt...............tbbbbbbbbt..',
  '..tbbt..............bbbbbbbbbb..',
  '.tbbbbt.............bbbbbbbbbbb.',
  '.tbbbbbt...........bbbbbbbbbbbbb',
  '.tbbbbbbt.....bbbbbbbbbbeebbbbbb',
  '..tbbbbbbbbbbbbbbbbbbbbbbbbbmmmm',
  '...bbbbbbbbbbbbbbbbbbbbbbbbbmmm.',
  '...bbbbbbbbbbbbbbbbbbbbbbbbbb...',
  '....bbbbbbbbbbbbbbbbbbbbbbbb....',
  '....BBbbbbbbbbbbbbbbbbbbbbb.....',
  '.....bbbbbbbbbbbbbbbbbbbbb......',
  '.....bbbbbbbbbbbbbbbbbbbb.......',
  '.....bbb..bbb....bbb..bbb.......',
  '.....bbb..bbb....bbb..bbb.......',
  '.....bbb..bbb....bbb..bbb.......',
  '.....bbb..bbb....bbb..bbb.......',
  '.....BBB..BBB....BBB..BBB.......',
  '....ssss.ssss...ssss.ssss.......',
  '................................',
  '................................',
];

// A small winged demon: horns, oversized head, stubby limbs.
export const IMP = [
  '....................',
  '...t............t...',
  '...tt..........tt...',
  '....bbbbbbbbbbbb....',
  '...bbbbbbbbbbbbbb...',
  '...bbebbbbbbbbebb...',
  '...bbbbbbbbbbbbbb...',
  '....bbbbmmbbbbbb....',
  '.....bbbbbbbbbb.....',
  '......bbbbbbbb......',
  'tt....bbbbbbbb....tt',
  'ttt..bbbbbbbbbb..ttt',
  '.tt..bbbbbbbbbb..tt.',
  '.....bbbbbbbbbb.....',
  '.....bbbbbbbbbb.....',
  '.....BBbbbbbbBB.....',
  '......bb....bb......',
  '......bb....bb......',
  '.....sss....sss.....',
  '....................',
];

// A low, four-legged shape: rats, boars, crawlers.
export const BEAST = [
  '........................',
  '..tt................tt..',
  '.thht..............thht.',
  '.thhht............thhht.',
  '..bbbbb..........bbbbb..',
  '...bbbbbbbbbbbbbbbbbb...',
  '..bbbbbbbbbbbbbbbbbbbb..',
  '..bbebbbbbbbbbbbbbbebb..',
  '..bbbbbbbbbbbbbbbbbbbb..',
  '..bbbbbbBBBBBBbbbbbbbb..',
  '...bbbbbbbbbbbbbbbbbb...',
  '...bbbbbbbbbbbbbbbbbb...',
  '...BBBbbbbbbbbbbbbBBB...',
  '...bb.bb........bb.bb...',
  '...bb.bb........bb.bb...',
  '...bb.bb........bb.bb...',
  '..sss.sss......sss.sss..',
  '........................',
];

// A soft, gelatinous mass: grubs, wisps, lurkers.
export const BLOB = [
  '........................',
  '.........bbbbbb.........',
  '.......bbbbbbbbbb.......',
  '......bbbbbbbbbbbb......',
  '.....bbbbbbbbbbbbbb.....',
  '....bbbbbbbbbbbbbbbb....',
  '....bbbebbbbbbbbebbb....',
  '....bbbbbbbbbbbbbbbb....',
  '....bbbbbbbbbbbbbbbb....',
  '....bbbbbBBBBbbbbbbb....',
  '.....bbbbbbbbbbbbbb.....',
  '.....BBbbbbbbbbbbBB.....',
  '......bbbbbbbbbbbb......',
  '.......BBBBBBBBBB.......',
  '........................',
  '........................',
];

// A dire wolf: half again the size of a wolf, with a spiked mane over hunched
// shoulders, a heavier jaw, and longer legs. An ascension has to read as "that is not
// the same animal" from across the viewport, so the change is in the SILHOUETTE and
// not the colour.
export const DIRE_WOLF = [
  '........................................',
  '............................t.....t.....',
  '..........t....t....t......ttt...ttt....',
  '..ttt.....tt...tt...tt.....tttbbbttt....',
  '.tttt....ttt..ttt..ttt....bbbbbbbbbbbbb.',
  '.ttttt...tttt.tttt.tttt..bbbbbbbbbbbbbbb',
  '.ttttt.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  '.tttttbbbbbbbbbbbbbbbbbbbbbbbbebbbbbbbbb',
  '..ttttbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmmm',
  '...tttbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmmm',
  '....ttbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmmmm.',
  '.....tbbbbbbbbbbbbbbbbbbbbbbbbbbbbmmmm..',
  '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....',
  '......bbbbbbbbbbbbbbbbbbbbbbbbbbbb......',
  '......BBbbbbbbbbbbbbbbbbbbbbbbbbb.......',
  '......bbbbbbbbbbbbbbbbbbbbbbbbbb........',
  '......bbbbbbbbbbbbbbbbbbbbbbbbb.........',
  '......BBBbbbbbbbbbbbbbbbbbbbbb..........',
  '......bbbbbbbbbbbbbbbbbbbbbbb...........',
  '......bbbbbbbbbbbbbbbbbbbbbb............',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......bbbb..bbbb...bbbb..bbbb...........',
  '......BBBB..BBBB...BBBB..BBBB...........',
  '.....sssss.sssss..sssss.sssss...........',
  '........................................',
  '........................................',
];

// A greater demon: the imp grown into something with real horns, a wingspan, and arms
// thick enough to swing. Hooves rather than feet.
export const DEMON = [
  '................................',
  '....t......................t....',
  '....tt....................tt....',
  '.....tt..................tt.....',
  '......tt................tt......',
  '.......tt..bbbbbbbbbb..tt.......',
  't.......ttbbbbbbbbbbbbtt.......t',
  'tt.......bbbbbbbbbbbbbb.......tt',
  'ttt......bbbebbbbbbebbb......ttt',
  'tttt.....bbbbbbbbbbbbbb.....tttt',
  'tttt.....bbmmmmmmmmmmbb.....tttt',
  'ttttt.....bbbbbbbbbbbb.....ttttt',
  'ttttt......bbbbbbbbbb......ttttt',
  'tttttt.......bbbbbb.......tttttt',
  'tttttt....bbbbbbbbbbbb....tttttt',
  'ttttttaaabbbbbbbbbbbbbbaaatttttt',
  'ttttttaaabbbbbbbbbbbbbbaaatttttt',
  '.tttttaaabbbbbbbbbbbbbbaaattttt.',
  '..ttttaaabbbbbbbbbbbbbbaaatttt..',
  '...tttaaabbbbbbbbbbbbbbaaattt...',
  '....ttaaabbbbbbbbbbbbbbaaatt....',
  '......fffbbbbbbbbbbbbbbfff......',
  '.........BBbbbbbbbbbbBB.........',
  '..........bbbbbbbbbbbb..........',
  '..........bbbb....bbbb..........',
  '..........bbbb....bbbb..........',
  '..........bbbb....bbbb..........',
  '..........BBBB....BBBB..........',
  '.........sssss....sssss.........',
  '................................',
];

// Each body carries its own cell size so they all end up a sensible height on screen.
export const BODIES = {
  humanoid: { grid: HUMANOID, cell: 2 },
  wolf:     { grid: WOLF,     cell: 4 },
  imp:      { grid: IMP,      cell: 4 },
  direwolf: { grid: DIRE_WOLF, cell: 4 },
  demon:    { grid: DEMON,    cell: 4 },
  beast:    { grid: BEAST,    cell: 5 },
  blob:     { grid: BLOB,     cell: 5 },
};
